name: restaurant_swipe_app
description: A Flutter application for swiping restaurants.
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0' # Adjust based on your Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
  flutter_card_swiper: ^6.0.0 # Assuming this version, adjust if different
  geolocator: ^9.0.0 # Assuming this version
  http: ^0.13.0 # Assuming this version
  url_launcher: ^6.0.0 # Assuming this version
  page_transition: ^2.0.0 # Assuming this version
  # Add Roboto font if not already present, e.g. google_fonts package
  # google_fonts: ^4.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
